spring.application.name=KSEP

spring.datasource.url=jdbc:mysql://localhost:3306/Ksep_db_local

spring.datasource.username=root

spring.datasource.password=Mukul@142005

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Replace with the email address you want to send from
spring.mail.username=your_millionminds_email@gmail.com
# Replace with your generated Google App Password (NO SPACES)
spring.mail.password=xxxx_xxxx_xxxx_xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true